name: Build Vanitygen++ (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libpcre3-dev libcurl4-openssl-dev

      - name: Build project (all binaries)
        run: make all

      - name: Verify vanitygen++
        run: ./vanitygen++ --help

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vanitygen-binaries
          path: |
            vanitygen++
            keyconv
            oclvanitygen++
            oclvanityminer
